spring:
  application:
    name: api-server
  profiles:
    active: local
  config:
    import:
      - optional:classpath:application-persistence.yml
      - optional:classpath:application-security.yml

logging:
  level:
    root: INFO
    kr.co.jparangdev.boardbuddy: DEBUG
  loki:
    url: ${LOKI_URL:http://localhost:3100}

# Swagger (OpenAPI)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
