sonar.projectKey=jparangdev_boardbuddies
sonar.organization=jparangdev
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/application/src/main,backend/presentation/api/src/main,backend/presentation/batch/src/main,backend/domain/src/main,backend/infrastructure/persistence/src/main,backend/infrastructure/client/src/main,backend/infrastructure/transients/src/main
sonar.tests=backend/application/src/test,backend/presentation/api/src/test,backend/domain/src/test
sonar.java.binaries=backend/application/build/classes,backend/presentation/api/build/classes,backend/presentation/batch/build/classes,backend/domain/build/classes,backend/infrastructure/persistence/build/classes,backend/infrastructure/client/build/classes,backend/infrastructure/transients/build/classes

# SQL files are often generated or contain unavoidable duplicates
sonar.exclusions=**/ddl/**,**/migration.sql

# PL/SQL rules customization
sonar.plsql.rules.disabled=plsql:S1192
