spring:
  application:
    name: api-server
  profiles:
    active: local
  config:
    import:
      - optional:classpath:application-persistence.yml
      - optional:classpath:application-transients.yml
      - optional:classpath:application-security.yml
      - optional:classpath:application-secret.yml

logging:
  level:
    root: INFO
    kr.co.jparangdev.boardbuddy: DEBUG
